adapting the Konnektor behavior to openfe.
OpenFreeEnergy/konnektor pull request #84
Opened 2024-10-22 14:10 UTC by RiesBen

if no scorer is provided to the max network planners, the std. behavior is to take the first possible mapping and be done. It used to use the last possible mapping.

this change is a minor adaptation to the old openFE behavior

2024-10-22 14:22 UTC, RiesBen commented
note Mac CI is failing currently everywhere in this Konnektor Repo, and we assume it is an rdkit version issue, if I understood it correctly, right @mikemhenry ?

2024-10-22 19:56 UTC, IAlibay requested changes
@RiesBen this PR seems to be missing tests, is this intentional?

2024-10-23 08:18 UTC, RiesBen commented
> @RiesBen this PR seems to be missing tests, is this intentional?

hmmmm... the thing is, the effect of the change was not tested before. 
So ideally one would add tests now. On the other hand this tries mainly to make the openFE-repo happy as the behavior is tested there.

I think it would be more beautiful to also test the behaviour here and I will try to add them if I have time.

2024-10-28 17:11 UTC, atravitz approved these changes

2024-10-28 17:27 UTC, atravitz commented
added as an issue [here](https://github.com/OpenFreeEnergy/konnektor/issues/89) so this PR is unblocked.

2024-10-28 17:41 UTC, atravitz commented on src/konnektor/network_planners/generators/maximal_network_generator.py
> +                            break
I am more concerned that this _is_ considered covered by tests, but the tests did not break when this change was made.

2024-11-15 22:00 UTC, atravitz commented
To clarify:

The prior behavior was to use the _first_ `mapping` of the _last_ `mapper` passed to `mappers`.

The current behavior takes the first `mapping` of the _first_ `mapper` passed to `mappers`.

In the case of multiple mappers, but no scorer, I think we should raise a warning. It might be confusing if a user is passing in multiple mappers and thinks both are being used, but it's quietly defaulting to the first mapper.

2025-03-04 19:41 UTC, IAlibay commented
> In the case of multiple mappers, but no scorer, I think we should raise a warning. It might be confusing if a user is passing in multiple mappers and thinks both are being used, but it's quietly defaulting to the first mapper.

That sounds like a good idea to me!

2025-05-14 23:41 UTC, atravitz commented
pre-commit.ci autofix

2025-05-14 23:45 UTC, atravitz commented
I think this is ready for a review. One outstanding issue (that is non-blocking), is that I warnings seem to be suppressed when using multiprocessing. Curious if anyone else has run into this, otherwise I will address it in a follow-up PR. 

Highest priority right now is getting behavior unified w/ openfe though.

2025-05-14 23:55 UTC, atravitz commented on src/konnektor/network_planners/generators/maximal_network_generator.py
> +                            break
covered now!

2025-05-15 14:27 UTC, IAlibay commented on src/konnektor/tests/network_planners/generators/test_maximal_network_planner.py
> +    # with pytest.warns(match="Only the first mapper provided will be used: <BadMulti"):
See: https://github.com/pytest-dev/pytest/issues/6745

2025-05-15 14:29 UTC, IAlibay commented on src/konnektor/network_planners/generators/star_network_generator.py
> +        From a robustness point of view, the Star Network, will immediately be disconnected if one `Transformation` fails.
Is it worth updating the docstring for mappers & scorer here?

2025-05-15 15:20 UTC, merged